// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package v1

import (
	fmt "fmt"
	errors "github.com/go-kratos/kratos/v2/errors"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

// 为某个枚举单独设置错误码
func IsIvalidParam(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_IVALID_PARAM.String() && e.Code == 401
}

// 为某个枚举单独设置错误码
func ErrorIvalidParam(format string, args ...interface{}) *errors.Error {
	return errors.New(401, ErrorReason_IVALID_PARAM.String(), fmt.Sprintf(format, args...))
}

func IsOrderReviewed(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_ORDER_REVIEWED.String() && e.Code == 301
}

func ErrorOrderReviewed(format string, args ...interface{}) *errors.Error {
	return errors.New(301, ErrorReason_ORDER_REVIEWED.String(), fmt.Sprintf(format, args...))
}

func IsOrderExsisted(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_ORDER_EXSISTED.String() && e.Code == 302
}

func ErrorOrderExsisted(format string, args ...interface{}) *errors.Error {
	return errors.New(302, ErrorReason_ORDER_EXSISTED.String(), fmt.Sprintf(format, args...))
}
